services:
  server:
    image: nginx:1.27.4-alpine
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mariadb
  php:
    build:
      context: docker
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mariadb:
    image: mariadb:latest
    env_file:
      - ./docker/env/mariadb.env
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

  # Utility containers
  composer:
    build:
      context: docker
      dockerfile: php.dockerfile
    entrypoint: "composer"
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: docker
      dockerfile: php.dockerfile
    entrypoint: ["php", "/var/www/html/artisan"]
    volumes:
      - ./src:/var/www/html
  # npm:
volumes:
  database:
